### ISSUE TITLE
It is possible to switch an empty inventory slot to an Item. 

### ISSUE THREAD

**Issue by RobertSzaszak** [finepointcgi/Godot-Horror-Game-GD#5]
If the player tries to move an empty inventory slot on top of an item the swap button function should not run.

**Comment by finepointcgi** [comment]
Thank you for all the bug reports! Ill be doing a follow up video fixing these issues!

**Comment by RobertSzaszak** [comment]
Its my pleasure! I am learning a lot from your videos.

**Comment by finepointcgi** [comment]
This issue has been fixed!
